writer_path: ./logs
checkpoint_path:

gpu_idx: 0

game_name: liars_dice
agent_name: prox

pi_network_kwargs:
  hidden_layers_sizes: [256, 256]

pi_optimizer_kwargs:
  optimizer_type: adam
  schedule:
    init_value: 0.0001
    end_value: 0.0001
  clip_gradient: 1.0
  optimizer_kwargs: 
    learning_rate: 0.0001
    b1: 0.9
    b2: 0.999

val_network_kwargs:
  hidden_layers_sizes: [256, 256]


val_optimizer_kwargs:
  optimizer_type: adam
  schedule:
    init_value: 0.0001
    end_value: 0.0001
  clip_gradient: 1.0
  optimizer_kwargs:  
    learning_rate: 0.0001
    b1: 0.9
    b2: 0.999

config_kwargs:
  batch_size: 256
  prox_cf: 0.2
  prox_period: 100_000
  prox_clip: 1.0
  prox_stop: -1
  ent_cf: 0.01
  ent_clip: 1.0
  eps_thr: 0.01
  zero_sum_reg: False
  adv_clip: 2.0
  gae_lambda: 0.75

agent_kwargs:
  seed: 123
  verbose: False


training_kwargs:
  budget: 20_000_000
  log_interval: 1_000
  eval_interval: 10_000
  checkpoint_interval: 1_000_000